### ISSUE TITLE
Incorrect dust calculation

### ISSUE THREAD

**Issue by Burzolog** [HearthSim/deck-code-bot#1]
I just saw [this post](https://www.reddit.com/r/hearthstone/comments/afl8jg/you_need_to_see_viper_pilot_his_homebrew_peanut/edzh3ub/?st=jqvnlw1r&sh=a966a60b) on r/hearthstone. The total dust according to the bot is 16140, which is wrong. The actual total dust cost is 16900.

**Comment by wccbuck** [comment]
Thanks man - Looks like total dust has been calculating incorrectly for months:

https://www.reddit.com/r/hearthstone/comments/adtcyk/gonking_the_lich_king_before_his_adventure/ee0okbi/?context=3: Says 2660, should be 2780

https://www.reddit.com/r/hearthstone/comments/afq188/lets_give_a_round_of_applause_for_this_weeks/ee0lpct/?context=3: Says 11500, should be 12960

I think I fixed it going forward, but I'm tempted to write a script that just goes back through old posts and edits the dust amount... Ugh. I really appreciate you bringing this to my attention!
