### ISSUE TITLE
Add /r/hs_duels to the subreddit list

### ISSUE THREAD

**Issue by wccbuck** [HearthSim/deck-code-bot#2]
I got a message from a moderator at /r/hs_duels asking to add that subreddit to deck-code-bot. @beheh could you do this? I believe `hs_duels` just needs to be appended to dcb_subreddit and then perhaps the bot needs to be relaunched, but I am not sure about that side of things. Thanks!

**Comment by beheh** [comment]
@wccbuck Hi there! I've added hs-duels to the server-side configuration and have restarted the bot. [It's live now](https://www.reddit.com/r/HS_Duels/comments/k61ghw/daily_duels_discussion_thread_4_golden_kobold/gekq2ra/?utm_source=reddit&utm_medium=web2x&context=3).

**Comment by wccbuck** [comment]
Thank you!
