### ISSUE TITLE
Bot seems to not be restarting on new commits

### ISSUE THREAD

**Issue by wccbuck** [HearthSim/deck-code-bot#5]
I made a [change](https://github.com/HearthSim/deck-code-bot/commit/837d529945454a3ee9e30b49c9704438c7558d3e) recently that should have gone into effect by now, but it appears as if deck-code-bot hasn't automatically restarted as it used to; I just ran a test, and a pre-change version (commit e077d88) replied to my deck code comment.

Could someone manually restart the bot? And potentially investigate the CI pipeline?

Thanks

**Comment by beheh** [comment]
Sorry for the delay, we were out. Should be updated now!
